version: '3.3'

services:
  app:
    build:
      context: .
    command: >
     sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web

  db:
    image: postgres:13-alpine
    container_name: storedb
    environment:
      - POSTGRES_DB=storedevdb
      - POSTGRES_USER=storedevuser
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pgdata:/var/lib/postgresql/data/

    ports:
      - 5432:5432

volumes:
  pgdata: